### PR TITLE
WL-1026 : A msg is public if it is public or its site is

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Announcements made on a .anon site should be public by default

This commit is twinned with that in the WL-1026 branch in wl-messages.

### CODE REVIEW

**Comment by buckett** [comment]
I think this one can probably be closed as ox-it/wl-message#1 should be all that is required.

**Comment by nicholaswilson100** [comment]
I'm not passing a site through now, I'm  doing a security check (as with WL-3544) and passing the result of that through.

**Comment by nicholaswilson100** [comment]
Security check in BaseMessage now.

(Is there a way on github of saying "This commit is supposed to be taken together with another commit in the WL-1026 branch in wl-messages." without saying it explicitly like that?), i..e, linking pull requests...

**Comment by buckett** [comment]
You can do issue linking in the comment with {reponame}#{pullRequestNumber}

**Comment by buckett** [comment]
I don't think this is needed any more so closing the pull request.

**Pull request closed without merging**
